FROM rust:1-slim-bookworm as builder
WORKDIR /app

RUN cargo install wasm-bindgen-cli
RUN rustup target add wasm32-unknown-unknown

COPY ./client .
COPY ./shared ./shared/
RUN ./bindgen.sh --release shooter3

FROM httpd
WORKDIR /app
COPY --from=builder /app/dist /usr/local/apache2/htdocs/
ENTRYPOINT ["httpd", "-D", "FOREGROUND"]
