FROM rust:1-slim-bookworm as builder
WORKDIR /app
COPY ./server .
COPY ./shared ./shared/
RUN cargo build --release --bin server --target-dir /app/build/

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/build/release/server /usr/local/bin
ENTRYPOINT ["/usr/local/bin/server"]
