[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = { version = "0.23" }
tokio = { version = "1", features = ["net", "rt-multi-thread", "macros", "time", "sync"] }
futures-util = "0.3.30"
shared = { path = "./shared" }
glam = "0.28.0"
